language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: Fqck/nuOq/3pkbaKFCnteRChNfPGWxoRLDHiHBW2nQOosWRY0keedxfWzkRL0J9zFPAqQXbeGp1NvVtXubUYfqDnjjrw1dg/A/3URnyXQ6VaSL18NDPn1nfk5wiRmygOAedMWLFVhFSzqFyMCb6pSoOgw4NMZgvLsh83KS0mi1lip4gsWtpfrQzK7KvOepj1MkUfiE4jr9/9A/s5J+VCnI/xoZ67TR23JQc+oX6lPcEW0lLmu7gotaY3LVF/wBjFWCXohhHLa4LXvEyYX8p3ArGF0uFhO7BV2//l/GVamrFmT1OAJwzoUaPJMUVxol1wlgAy1GkQzEv4LB3IWnTTQVJVrkdxkyVCehOkzvIVdBKZixZuHqIBJnbHAVO6HriULMZb9vcSSbHQFLXwf0L4ikzYjARkcQX2j9I7SAePIy1feG6oxmPR1l06fagmPQPswnm+gQUI66LwE722bNzdms/5etjE+ZNa9JlXe1goDbgEFLxs7YEhdSaDoinmX/NzWZJJHRhj6/zdzdweomNpdH3GBc/oLCwgH6oDvFFhZhIMoX+sNWh7k7Hh449XrJ7M2tjhBp/UhRLKVsQL1GZqix1tRmYtdt5LdvvmKQffYrAzAjuPvdvkoDIaIhSZhm3dq5mDslv0kSqPM/jfByjvDBLzsM9I6RyhqYcu9WJw9xc=
